replicaCount: 2

image:
  repository: 051826736527.dkr.ecr.us-east-2.amazonaws.com/order-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

readinessProbe:
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5

livenessProbe:
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
